"""
Generate notes define
"""
if __name__ == '__main__':

    base_notes = ['C', 'CS', 'D', 'DS', 'E', 'F', 'FS', 'G', 'GS', 'A', 'AS', 'B']
    num_notes = len(base_notes)
    count = 12
    with open('note/notes_defines.py', 'w') as f:
        f.write('\"\"\"\n\nNotes defines, user-friendly way to use notes\nC4 is better than 60\nAlso musicians aren\'t'
                ' programmers...\n'
                'Generated by ' + str(__file__).replace('\\', '\\\\') + '\n\n\"\"\"\n\n')
        f.write('class NoteDefines:\n')
        for i in range(9):
            f.write('    # Octave: {0}\n'.format(i))
            for n in base_notes:
                f.write('    {note}{octave} = {midi_id}\n'.format(note=base_notes[count%num_notes], octave=i, midi_id=count))
                count += 1
            f.write('\n\n')
